apiVersion: v2
name: sa-keycloak
description: Service Autenthicator Helm chart for Keycloak
# Type of the Helm chart
type: application
# Helm chart version
version: 0.1.0
# Keycloak version
appVersion: "12.0.2"

# Dependencies
dependencies:
  - name: postgresql
    version: 10.2.5
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled